cmake_minimum_required(VERSION 4.0)

include(GNUInstallDirs)
set(CMAKE_C_STANDARD 23)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)

if (EMSCRIPTEN)
    set(BUILD_SHARED_LIBS OFF)
    set(CGLM_SHARED OFF)
    set(GLFW_LIBRARY_TYPE STATIC)
else()
    set(BUILD_SHARED_LIBS ON)
    set(CGLM_SHARED ON)
    set(GLFW_LIBRARY_TYPE SHARED)
endif()

set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
set(CMAKE_BUILD_WITH_INSTALL_RPATH OFF)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)

set(COMPILER_FLAGS
    -fPIC
    -Wpedantic
    -Werror
    -Wall
    -Wextra
)
